"""archive

Revision ID: 6c0710e27d01
Revises: 34e3e4c5c89f
Create Date: 2022-02-15 21:13:02.181914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0710e27d01'
down_revision = '34e3e4c5c89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('archive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_model', 'archive')
    # ### end Alembic commands ###
