"""empty message

Revision ID: 831c42943f50
Revises: 6c0710e27d01
Create Date: 2022-02-16 19:07:46.917440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831c42943f50'
down_revision = '6c0710e27d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('archived', sa.Boolean(), server_default=sa.text('0'), nullable=True))
    op.drop_column('note_model', 'archive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('archive', sa.BOOLEAN(), nullable=True))
    op.drop_column('note_model', 'archived')
    # ### end Alembic commands ###
